background {
    monitor =
    path = screenshot  # Oppure il percorso a uno sfondo fisso
    blur_passes = 2
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.25 # Dimensione dei pallini
    dots_spacing = 0.15
    dots_center = true
    fade_on_empty = false
    
    font_color = rgb(ebdbb2)
    inner_color = rgb(3c3836)   # Sfondo scuro (stile Gruvbox)
    outer_color = rgb(d65d0e)   # Bordo colorato
    check_color = rgb(fabd2f)
    fail_color = rgb(cc241d)
    
    placeholder_text = <i>Inserisci password...</i>
    hide_input = false
}
